CREATE DATABASE IF NOT EXISTS eletrodomesticos_saep_db;
USE eletrodomesticos_saep_db;

-- TABELA USUARIO
CREATE TABLE USUARIO (
    USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255),
    USU_EMAIL VARCHAR(255) UNIQUE,
    USU_SENHA VARCHAR(255)
);

-- TABELA ELETRODOMESTICO
CREATE TABLE ELETRODOMESTICO (
    ELETRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    ELETRO_NOME VARCHAR(255),
    ELETRO_DESCRICAO VARCHAR(255),
    ELETRO_FORNECEDOR VARCHAR(255),
    ELETRO_CATEGORIA VARCHAR(255),
    ELETRO_POTENCIA VARCHAR(255),
    ELETRO_CONSUMO_ENERGETICO VARCHAR(255),
    ELETRO_GARANTIA VARCHAR(255),
    ELETRO_PRIORIDADE_REPOSICAO VARCHAR(255),
    FK_USU_ID INT,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIO(USU_ID)
);

-- TABELA ESTOQUE
CREATE TABLE ESTOQUE (
    ESTOQUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QUANTIDADE INT,
    ESTOQUE_LIMITE_MINIMO INT,
    FK_ELETRO_ID INT,
    FOREIGN KEY (FK_ELETRO_ID) REFERENCES ELETRODOMESTICO(ELETRO_ID)
);

-- TABELA LOGS
CREATE TABLE LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255) NOT NULL,
    LOG_DATA_HORA DATETIME,
    LOG_TIPO VARCHAR(50),
    FK_USU_ID INT,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIO(USU_ID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES
('Matheus', 'matheus@gmail.com', '12345678'),
('Moroni', 'moroni@gmail.com', '000000000'),
('David', 'david@gmail.com', 'David69');

INSERT INTO ELETRODOMESTICO (ELETRO_NOME, ELETRO_DESCRICAO, ELETRO_FORNECEDOR, ELETRO_CATEGORIA, ELETRO_POTENCIA, ELETRO_CONSUMO_ENERGETICO, ELETRO_GARANTIA, ELETRO_PRIORIDADE_REPOSICAO, FK_USU_ID)
VALUES
('Geladeira', 'Geladeira frost free 400L', 'Brastemp', 'Refrigeradores', '150W', 'Classe A', '2 anos', 'Alta', 1),
('Fogão', 'Fogão 4 bocas a gás', 'Consul', 'Cozinha', '200W', 'Classe B', '1 ano', 'Média', 2),
('Micro-ondas', 'Micro-ondas 30L', 'Electrolux', 'Cozinha', '1200W', 'Classe A', '1 ano', 'Baixa', 3);

INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, ESTOQUE_LIMITE_MINIMO, FK_ELETRO_ID)
VALUES
(120, 50, 1),
(85, 30, 2),
(60, 20, 3);

INSERT INTO LOGS (LOG_DESCRICAO, LOG_DATA_HORA, LOG_TIPO, FK_USU_ID)
VALUES
('Entrada de geladeiras', '2023-10-01 10:00:00', 'ENTRADA', 1),
('Saída de fogões', '2023-10-02 11:00:00', 'SAIDA', 2),
('Devolução de micro-ondas', '2023-10-03 12:00:00', 'DEVOLUCAO', 3);
